### PR TITLE
Update to support celery 3 and celery 4 option parsing

### PR DESCRIPTION
**Pull request by jpunwin**
Tweak to the config parser to support both celery 3 and 4

### CODE REVIEW

**Comment by jpunwin** [comment]
Not sure if there is a way to merge this with #59

**Comment by alexsv** [comment]
+1 for this change

**Comment by przemal** [comment]
@jpunwin Closed #59, so this can be merged instead

**Comment by alexsv** [comment]
Guys, is it going to be merged?

**Comment by jpunwin** [comment]
*Shrug* still waiting on approval

**Comment by sontek** [comment]
This is released on pypi as `pyramid_celery 3.0.0` with some other fixes that I had in the queue!  Thanks for the contribution

**Pull request merged**
